config/routes.rb
Rails.application.routes.draw do
  root to: 'courses#menu'
  post 'courses/menu'
  get 'courses/index'
  get 'courses/show'
  get 'courses/new'
  post 'courses/new'
  post 'courses/confirm'
  post 'courses/create'
  get 'courses/edit'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
end

app/models/course_create_form.rb
class CourseCreateForm
    include ActiveModel::Model

    attr_accessor :course_no, :course_name, :the_date, :year, :month, :date,
        :start_time, :start_hour, :start_minute,
        :end_time, :end_hour, :end_minute, :capacity
    
    validates :course_no, presence: true, length: { maximum: 4 }
    validates :course_name, presence: true, length: { maximum: 40 }
    validates :capacity, presence: true, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 50 }
    validate :end_is_later_than_start

    private

    def end_is_later_than_start
        if (start_hour + start_minute).to_i > (end_hour + end_minute).to_i
            errors.add(:end_time, ' 「終了時刻」は「開始時刻」よりも後の時刻を入力してください')
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/courses_controller.rb
require "date"
require "course"

class CoursesController < ApplicationController
  def index
  end

  def show
  end

  def new
    @course_create_form = CourseCreateForm.new
    @year = Date.today.year
  end

  def confirm
    if params[:back].present?
      render :menu
      return
    else 
      @course_create_form = CourseCreateForm.new(course_create_form_params)
      @year = Date.today.year
      render :new unless @course_create_form.valid?
    end
  end

  def create
    @course_create_form = CourseCreateForm.new(course_create_form_params)
    if params[:back].present?
      @year = Date.today.year
      render :new
    else
      @course = Course.new
      form_to_model(course_create_form_params, @course)
      p @course
      @course.save!
      render :create
      return
    end
  end

  def complete
    if params[:menu].present?
      render :menu
    elsif params[:new]
      @year = Date.today.year
      render :new
    end
  end
  
  def edit
  end

  private

  def course_create_form_params
    params.require(:course_create_form).permit(:course_no, :course_name, :year, :month, :date, 
      :start_hour, :start_minute, :end_hour, :end_minute, :capacity)
  end

  def form_to_model(form, course)
    course_create_form = CourseCreateForm.new(form)
    course.course_no = course_create_form.course_no
    course.course_name = course_create_form.course_name
    course.the_date = course_create_form.year + "-" + course_create_form.month + "-" + course_create_form.date
    course.start_time = course_create_form.start_hour + ":" + course_create_form.start_minute
    course.end_time = course_create_form.end_hour + ":" + course_create_form.end_minute
    course.capacity = course_create_form.capacity
    course.inp_date = Date.today
    course.upd_date = Time.now
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/confirm.html.slim
h1.txt-center.blue 登録確認
p.txt-center 入力内容を確認してください。

= form_with model: @course_create_form, local: true, url: courses_create_path do |f|
    div.txt-center
        table.tbl-center
            tr
                td= f.label :course_no
                td= @course_create_form.course_no
                = f.hidden_field :course_no
            tr
                td= f.label :course_name
                td= @course_create_form.course_name
                = f.hidden_field :course_name
            tr
                td= f.label :the_date
                td
                    = @course_create_form.year
                    = f.hidden_field :year
                    | 年
                    = @course_create_form.month
                    = f.hidden_field :month
                    | 月
                    = @course_create_form.date
                    = f.hidden_field :date
                    | 日
            tr
                td= f.label :start_time
                td
                    = @course_create_form.start_hour
                    = f.hidden_field :start_hour
                    | 時
                    = @course_create_form.start_minute
                    = f.hidden_field :start_minute
                    | 分
                = f.hidden_field :start_time
            tr
                td= f.label :end_time
                td
                    = @course_create_form.end_hour
                    = f.hidden_field :end_hour
                    | 時
                    = @course_create_form.end_minute
                    = f.hidden_field :end_minute
                    | 分
                = f.hidden_field :end_time
            tr
                td= f.label :capacity
                td= @course_create_form.capacity
                = f.hidden_field :capacity
                    | 人
        = f.submit '戻る', name: 'back', class: 'blue'
        = f.submit '登録', class: 'blue'

app/views/courses/create.html.slim
h1.txt-center.blue 登録完了
p.txt-center.blue 講座登録を完了しました。

div.txt-center
    form
        table.tbl-center
            tr
                td
                    button.blue formaction=root_path
                        | メニュー
            tr
                td
                    button.blue formaction=courses_new_path
                        | もう一度登録

app/views/courses/edit.html.slim
h1 Courses#edit
p Find me in app/views/courses/edit.html.slim

app/views/courses/index.html.slim
h1 Courses#index
p Find me in app/views/courses/index.html.slim

app/views/courses/menu.html.slim
h1.txt-center.blue
    | 講座管理メニュー
p.txt-center
    | 「講座登録」または「講座修正・削除」ボタンを押してください。

div.txt-center
    form
        table.tbl-center
            tr
                td
                    button.blue formaction=courses_new_path
                        | 講座登録
            tr
                td
                    button.blue formaction=courses_edit_path
                        | 講座修正・削除

app/views/courses/new.html.slim
h1.txt-center.blue 講座登録
p.txt-center ※ は入力必須です。

- if @course_create_form.errors.present?
    ul.txt-center
        - @course_create_form.errors.full_messages.each do |message|
            li= message

div.txt-center
    = form_with model: @course_create_form, local: true, url: courses_confirm_path do |f|
        table align="center"
            tr
                td 
                    = f.label :course_no
                    span ※
                td
                    = f.text_field :course_no, id: 'course_no'
            tr
                td
                    = f.label :course_name
                    span ※
                td
                    = f.text_field :course_name, id: 'course_name'
            tr
                td
                    = f.label :the_date
                    span ※
                td
                    = f.select :year, (@year..@year+5).map{|n| ["#{n}", n]}, id: 'the_date'
                    | 年
                    = f.select :month, (1..12).map{|n| ["#{n}", n]}, id: 'the_date' 
                    | 月
                    = f.select :date, (1..31).map{|n| ["#{n}", n]}, id: 'the_date'
                    | 日
            tr
                td
                    = f.label :start_time
                    span ※
                td
                    = f.select :start_hour, (10..18).map{|n| ["#{n}", n]}, id: 'start_time'
                    | 時
                    = f.select :start_minute, {"00":"00", "30":"30"}, id: 'start_time'
                    | 分
            tr
                td
                    = f.label :end_time
                    span ※
                td
                    = f.select :end_hour, (10..18).map{|n| ["#{n}", n]}, id: 'end_time'
                    | 時
                    = f.select :end_minute, {"00":"00", "30":"30"}, id: 'end_time'
                    | 分
            tr
                td
                    = f.label :capacity
                    span ※
                td
                    = f.text_field :capacity, id: 'capacity'
                    | 人
        = f.submit '戻る', name: 'back', class: 'blue'
        = f.submit '確認', class: 'blue'

app/views/courses/show.html.slim
h1 Courses#show
p Find me in app/views/courses/show.html.slim

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | CourseManagementRb
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = yield